### ISSUE TITLE
Exception when learning rf

### ISSUE THREAD

**Issue by kungfo0** [mlfunston/node-red-contrib-broadlink#14]
When using learn with rf-sweep the following exception is thrown:
```12 May 15:59:24 - [warn] [RM:Broadlink rff] Please keep long press on the remote button until scan finishes.
12 May 15:59:29 - [warn] [RM:Broadlink rff] Please tap the remote button.
12 May 15:59:54 - [red] Uncaught Exception:
12 May 15:59:54 - TypeError: Cannot read property 'checkRFData2' of null
    at Timeout._onTimeout (/config/node-red/node_modules/node-red-contrib-broadlink-control/nodes/RMNode.js:58:63)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)```

**Comment by mlfunston** [comment]
Ok, will look into it when I get a chance, but I can't test it. I may need to send you a Beta version to check it. Probably next week or two.

**Comment by cacherocks** [comment]
I have the same problem.

**Comment by richard-kramer** [comment]
Got the same problem.

**Comment by mlfunston** [comment]
Updated in v1.0.8
