### ISSUE TITLE
broadlink control crashes with SP3 devices

### ISSUE THREAD

**Issue by vladtsit** [mlfunston/node-red-contrib-broadlink#52]
Hi!

I have several SP3 devices that worked properly. After long time I decided to update boradlink-control and as result node-red periodically (2-3 time a day) crashes with following log:
9 Aug 14:47:04 - [red] Uncaught Exception:
9 Aug 14:47:04 - Error: error:0606508A:digital envelope routines:EVP_DecryptFinal_ex:data not multiple of block length
    at Decipheriv.final (internal/crypto/cipher.js:164:28)
    at Socket.Device.cs.on (c:\Users\vladtsit\.node-red\node_modules\node-red-contrib-broadlink-control\nodes\Device.js:33:31)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)

How I can correct it?
regards,
Vladimir

**Comment by mlfunston** [comment]
Did you manage to fix this?

As far as I can see, this is a problem with the data encrypted in the stream sent from the unit that is the wrong length? Perhaps an issue with one of the units maybe?

**Comment by vladtsit** [comment]
I was not able to manage the problem. Just decided to temporary remove SP3 devices. May be one of 4 devices sporadically send wrong data but it is very difficult to debug because it happens rarely. Could you please just catch and ignore such error? At least it will not stop node-red.
